In [90]:
import pandas as pd
import numpy as np

In [91]:
a = pd.read_csv('D:\\Python\\TekWorks\\Week_6\\amazon_laptop_price_dataset.csv')
df = pd.DataFrame(a)
df.head()

,Brand,Processor,RAM_GB,Storage_GB,Operating_System,GPU,Rating,Price_USD
0,MSI,AMD Ryzen 3,4,512,macOS,AMD Radeon,4.2,1092.04
1,Lenovo,Intel i7,32,128,macOS,NVIDIA GTX 1650,3.1,1934.84
2,Asus,AMD Ryzen 7,8,256,Windows 10,Integrated,3.6,758.86
3,Dell,Intel i7,16,512,Windows 11,AMD Radeon,3.6,1430.88
4,MSI,AMD Ryzen 7,8,512,Windows 11,NVIDIA RTX 3050,3.8,1457.77

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             1000 non-null   object
 1   Processor         1000 non-null   object
 2   RAM_GB            1000 non-null   int64
 3   Storage_GB        1000 non-null   int64
 4   Operating_System  1000 non-null   object
 5   GPU               1000 non-null   object
 6   Rating            1000 non-null   float64
 7   Price_USD         1000 non-null   float64
dtypes: float64(2), int64(2), object(4)
memory usage: 62.6+ KB

In [65]:
df.describe()

            RAM_GB   Storage_GB       Rating    Price_USD
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     15.252000   460.032000     4.030300  1462.197300
std      10.693683   336.083691     0.580852   479.697515
min       4.000000   128.000000     3.000000   404.830000
25%       8.000000   128.000000     3.500000  1101.552500
50%      16.000000   256.000000     4.100000  1421.705000
75%      32.000000   512.000000     4.500000  1793.382500
max      32.000000  1024.000000     5.000000  2896.850000

In [92]:
df['Indian_Rupees'] = df['Price_USD']*92

In [93]:
df.drop('Price_USD',axis=1,inplace=True)

In [68]:
df.head()

,Brand,Processor,RAM_GB,Storage_GB,Operating_System,GPU,Rating,Indian_Rupees
0,MSI,AMD Ryzen 3,4,512,macOS,AMD Radeon,4.2,100467.68
1,Lenovo,Intel i7,32,128,macOS,NVIDIA GTX 1650,3.1,178005.28
2,Asus,AMD Ryzen 7,8,256,Windows 10,Integrated,3.6,69815.12
3,Dell,Intel i7,16,512,Windows 11,AMD Radeon,3.6,131640.96
4,MSI,AMD Ryzen 7,8,512,Windows 11,NVIDIA RTX 3050,3.8,134114.84

In [69]:
import seaborn as sns
sns.boxplot(data=df)

In [94]:
Q1=df['Indian_Rupees'].quantile(0.25)
Q3=df['Indian_Rupees'].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
df=df[(df['Indian_Rupees'] >= lower_bound) &(df['Indian_Rupees']<= upper_bound)]

In [71]:
df.head()

,Brand,Processor,RAM_GB,Storage_GB,Operating_System,GPU,Rating,Indian_Rupees
0,MSI,AMD Ryzen 3,4,512,macOS,AMD Radeon,4.2,100467.68
1,Lenovo,Intel i7,32,128,macOS,NVIDIA GTX 1650,3.1,178005.28
2,Asus,AMD Ryzen 7,8,256,Windows 10,Integrated,3.6,69815.12
3,Dell,Intel i7,16,512,Windows 11,AMD Radeon,3.6,131640.96
4,MSI,AMD Ryzen 7,8,512,Windows 11,NVIDIA RTX 3050,3.8,134114.84

In [72]:
df.shape

(996, 8)

In [73]:
col = ['Brand','Processor','RAM_GB']
for c in col:
    print(c)
    print(df[c].value_counts())

Brand
Brand
Apple     154
MSI       149
Asus      144
Dell      144
Acer      142
HP        132
Lenovo    131
Name: count, dtype: int64
Processor
Processor
AMD Ryzen 7    182
Intel i5       176
AMD Ryzen 5    173
AMD Ryzen 3    158
Intel i7       157
Intel i3       150
Name: count, dtype: int64
RAM_GB
RAM_GB
8     263
16    254
32    252
4     227
Name: count, dtype: int64

In [95]:
mapping = {
    "Windows 10" : 0,
    "Windows 11" : 0,
    'macOS' : 1
}
df['Operating_System']=df['Operating_System'].map(mapping)
df.Operating_System.unique()

array([1, 0])

In [75]:
df.sample(10)

,Brand,Processor,RAM_GB,Storage_GB,Operating_System,GPU,Rating,Indian_Rupees
944,Dell,AMD Ryzen 7,32,512,1,NVIDIA RTX 3050,3.8,211209.92
403,Lenovo,AMD Ryzen 3,8,128,0,Integrated,3.9,55165.04
693,Asus,Intel i5,4,1024,1,Integrated,4.6,162269.60
608,MSI,Intel i7,4,1024,0,NVIDIA RTX 3050,4.4,169745.52
250,Lenovo,AMD Ryzen 7,32,256,0,NVIDIA GTX 1650,4.9,167763.84
497,HP,Intel i7,4,1024,0,AMD Radeon,3.4,133734.88
904,HP,AMD Ryzen 5,4,256,0,NVIDIA RTX 3050,4.4,97898.12
4,MSI,AMD Ryzen 7,8,512,0,NVIDIA RTX 3050,3.8,134114.84
723,Acer,Intel i5,32,256,0,AMD Radeon,4.7,119304.68
560,Lenovo,Intel i5,16,128,0,Integrated,3.7,90945.68

In [76]:
df.Processor.unique()

array(['AMD Ryzen 3', 'Intel i7', 'AMD Ryzen 7', 'Intel i5', 'Intel i3',
       'AMD Ryzen 5'], dtype=object)

In [77]:
df.GPU.unique()

array(['AMD Radeon', 'NVIDIA GTX 1650', 'Integrated', 'NVIDIA RTX 3050'],
      dtype=object)

In [96]:
df['GPU'] = df['GPU'].replace({
    'AMD Radeon': 1,
    'NVIDIA GTX 1650': 2,
    'Integrated': 3,
    'NVIDIA RTX 3050': 4
})
df['GPU'].unique()

C:\Users\vinee\AppData\Local\Temp\ipykernel_13708\3807723391.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['GPU'] = df['GPU'].replace({

array([1, 2, 3, 4])

In [79]:
df.head()

,Brand,Processor,RAM_GB,Storage_GB,Operating_System,GPU,Rating,Indian_Rupees
0,MSI,AMD Ryzen 3,4,512,1,None,4.2,100467.68
1,Lenovo,Intel i7,32,128,1,None,3.1,178005.28
2,Asus,AMD Ryzen 7,8,256,0,None,3.6,69815.12
3,Dell,Intel i7,16,512,0,None,3.6,131640.96
4,MSI,AMD Ryzen 7,8,512,0,None,3.8,134114.84

In [97]:
df['Processor'] = df['Processor'].replace({
    'AMD Ryzen 3': 1,
    'Intel i7': 2,
    'AMD Ryzen 7': 3,
    'Intel i5': 4,
    'Intel i3': 5,
    'AMD Ryzen 5': 6
})
df['Processor'].unique()

C:\Users\vinee\AppData\Local\Temp\ipykernel_13708\444782597.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Processor'] = df['Processor'].replace({

array([1, 2, 3, 4, 5, 6])

In [81]:
df.head()

,Brand,Processor,RAM_GB,Storage_GB,Operating_System,GPU,Rating,Indian_Rupees
0,MSI,None,4,512,1,None,4.2,100467.68
1,Lenovo,None,32,128,1,None,3.1,178005.28
2,Asus,None,8,256,0,None,3.6,69815.12
3,Dell,None,16,512,0,None,3.6,131640.96
4,MSI,None,8,512,0,None,3.8,134114.84

In [82]:
df.head()

,Brand,Processor,RAM_GB,Storage_GB,Operating_System,GPU,Rating,Indian_Rupees
0,MSI,None,4,512,1,None,4.2,100467.68
1,Lenovo,None,32,128,1,None,3.1,178005.28
2,Asus,None,8,256,0,None,3.6,69815.12
3,Dell,None,16,512,0,None,3.6,131640.96
4,MSI,None,8,512,0,None,3.8,134114.84

In [98]:
from sklearn.preprocessing import LabelEncoder

encode_cols = ['Brand', 'Processor', 'GPU', 'Operating_System']
for c in encode_cols:
    le = LabelEncoder()
    df[c] = le.fit_transform(df[c].astype(str))

df[encode_cols].head()

   Brand  Processor  GPU  Operating_System
0      6          0    0                 1
1      5          1    1                 1
2      2          2    2                 0
3      3          1    0                 0
4      6          2    3                 0

In [99]:
df = df.dropna().copy()
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [100]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=44)

In [101]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [102]:
y_pred = model.predict(x_test)

In [103]:
from sklearn.metrics import r2_score
score = r2_score(y_test,y_pred)
score

0.8048436319443968

In [105]:
import pickle

model_path = r'D:\Python\TekWorks\Week_6\model.pkl'
with open(model_path, 'wb') as file:
    pickle.dump(model, file)

print(f'Model saved to: {model_path}')

Model saved to: D:\Python\TekWorks\Week_6\model.pkl